### ISSUE TITLE
using any occ geoblocker command leads to unhandled exception

### ISSUE THREAD

**Issue by rcfa** [HomeITAdmin/nextcloud_geoblocker#124]
I have tried several occ commands, and they all end up throwing exceptions: (note occ is an alias, so it does the proper thing)

`alias occ="sudo -u www-data php -d memory_limit=512M /var/www/nextcloud/occ"`

```
# occ geoblocker:localization-service:reset-db 2
Starting reset of the database.
Reset was successful.
An unhandled exception has been thrown:
TypeError: Return value of "OCA\GeoBlocker\Command\LocalizationService\ResetDB::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/nextcloud/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run()
#4 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#5 /var/www/nextcloud/occ(11): require_once('...')
#6 {main}                                                                                                                 

```

```
# occ geoblocker:localization-service:u          
Starting update of the database. This may take very long.
Update was successful.
An unhandled exception has been thrown:
TypeError: Return value of "OCA\GeoBlocker\Command\LocalizationService\UpdateDB::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/nextcloud/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run()
#4 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#5 /var/www/nextcloud/occ(11): require_once('...')
#6 {main}                                    

```

```
# occ geoblocker:localization-service:li

0: GeoIPLookup (local) [Active]
1: MaxMindGeoLite2 (local)
2: RIRData (local)
3: Dummy  (default)

An unhandled exception has been thrown:
TypeError: Return value of "OCA\GeoBlocker\Command\LocalizationService\ListServices::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#3 /var/www/nextcloud/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run()
#4 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#5 /var/www/nextcloud/occ(11): require_once('...')
#6 {main} 
```

**Comment by HomeITAdmin** [comment]
Hi, please try the latest version 0.5.13.

**Comment by rcfa** [comment]
I'll test as soon as it's available for download from the app store, there it's still 0.5.12, and I don't want to mess up the automatic update system my installing something behind its back...

**Comment by HomeITAdmin** [comment]
You are right, I did a mistake in the deployment. Should be available now.

**Comment by rcfa** [comment]
Thanks! Looks like it's fixed! 👍🏻
